name: Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black flake8

      - name: Run Black (format check)
        run: |
          black --check .

      - name: Run Flake8 (lint)
        run: |
          flake8 .
